name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  Linux:
    strategy:
      fail-fast: false
      matrix:
        target:
          - linux-x86_64-static
          - linux-x86_64-dyn
          - win32-static
          - win32-dyn
        include:
          - target: linux-x86_64-static
            image_variant: focal
            lib_postfix: '/x86_64-linux-gnu'
            arch_name: linux-x86_64
          - target: linux-x86_64-dyn
            image_variant: focal
            lib_postfix: '/x86_64-linux-gnu'
            arch_name: linux-x86_64
          - target: win32-static
            image_variant: f35
            lib_postfix: '64'
            arch_name: i686-w64-mingw32
          - target: win32-dyn
            image_variant: f35
            lib_postfix: '64'
            arch_name: i686-w64-mingw32
    env:
      HOME: /home/runner
    runs-on: ubuntu-latest
    container:
      image: "ghcr.io/kiwix/kiwix-build_ci_${{matrix.image_variant}}:36"
    steps:
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install dependencies
      uses: kiwix/kiwix-build/actions/dl_deps_archive@main
      with:
        target_platform: ${{ matrix.target }}
    - name: Compile
      shell: bash
      run: |
        if [[ "${{matrix.target}}" =~ .*-static ]]; then
          MESON_OPTION="-Dstatic-linkage=true"
        else
          MESON_OPTION=""
        fi
        if [ -e "$HOME/BUILD_${{matrix.arch_name}}/meson_cross_file.txt" ]; then
          MESON_OPTION="$MESON_OPTION --cross-file $HOME/BUILD_${{matrix.arch_name}}/meson_cross_file.txt"
        fi
        meson . build ${MESON_OPTION}
        cd build
        ninja
      env:
        PKG_CONFIG_PATH: "${{env.HOME}}/BUILD_${{matrix.arch_name}}/INSTALL/lib/pkgconfig:${{env.HOME}}/BUILD_${{matrix.arch_name}}/INSTALL/lib${{matrix.lib_postfix}}/pkgconfig"
        CPPFLAGS: "-I${{env.HOME}}/BUILD_${{matrix.arch_name}}/INSTALL/include"
